package com.mojang.minecraftVN;

import android.animation.*;
import android.app.*;
import android.app.Activity;
import android.content.*;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.media.SoundPool;
import android.net.*;
import android.net.Uri;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.widget.*;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.TextView;
import androidx.annotation.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.cardview.widget.CardView;
import androidx.fragment.app.DialogFragment;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import androidx.webkit.*;
import com.blogspot.atifsoftwares.animatoolib.*;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.FirebaseApp;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.ChildEventListener;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.GenericTypeIndicator;
import com.google.firebase.database.ValueEventListener;
import com.zip4j.*;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Timer;
import java.util.TimerTask;
import java.util.regex.*;
import org.json.*;
import android.net.Uri;
import android.widget.ImageView;
import com.bumptech.glide.Glide;
import android.os.Bundle;
import android.view.View;
import androidx.appcompat.app.AppCompatActivity;
import android.app.Activity;
import android.widget.SeekBar;
import android.widget.TextView;
// Import các thư viện cần thiết;

public class JavalauncherActivity extends AppCompatActivity {
	
	private Timer _timer = new Timer();
	private FirebaseDatabase _firebase = FirebaseDatabase.getInstance();
	
	private double sef = 0;
	private boolean a = false;
	
	private ArrayList<HashMap<String, Object>> inf = new ArrayList<>();
	
	private LinearLayout linear1;
	private LinearLayout linear2;
	private LinearLayout linear5;
	private LinearLayout accountbutton;
	private LinearLayout linear10;
	private LinearLayout bedrock;
	private LinearLayout linear12;
	private LinearLayout linear8;
	private LinearLayout accountwhite;
	private ImageView imageview5;
	private TextView playername;
	private LinearLayout newwhite;
	private ImageView imageview2;
	private TextView textview5;
	private LinearLayout mainwhite;
	private ImageView imageview3;
	private TextView textview4;
	private LinearLayout communitywhite;
	private ImageView imageview4;
	private TextView textview3;
	private LinearLayout linear133;
	private LinearLayout linear13;
	private LinearLayout newswhite;
	private ImageView imageview44;
	private TextView moi;
	private LinearLayout settingwhite;
	private ImageView imageview7;
	private TextView textview2;
	private LinearLayout linear15;
	private LinearLayout navigationbar;
	private LinearLayout javabr;
	private LinearLayout settingsbr;
	private LinearLayout skinmenu;
	private LinearLayout accountmenu;
	private ScrollView vscroll1;
	private TextView title;
	private LinearLayout nut1;
	private LinearLayout nut2;
	private LinearLayout nut3;
	private LinearLayout nut4;
	private LinearLayout nut5;
	private LinearLayout nut6;
	private LinearLayout nut7;
	private TextView textview8;
	private LinearLayout Thanhxanh1;
	private TextView textview24;
	private LinearLayout thanhxanh2;
	private TextView textview25;
	private LinearLayout thanhxanh3;
	private TextView textview26;
	private LinearLayout thanhxanh4;
	private TextView textview34;
	private LinearLayout thanhxanh5;
	private TextView textview79;
	private LinearLayout thanhxanh6;
	private TextView textview78;
	private LinearLayout thanhxanh7;
	private LinearLayout linear45;
	private LinearLayout linear42;
	private LinearLayout linear40;
	private ImageView imageview23;
	private ScrollView keover;
	private TextView srr;
	private LinearLayout linear161;
	private LinearLayout ver1;
	private LinearLayout ver2;
	private LinearLayout ver3;
	private LinearLayout ver4;
	private LinearLayout ver5;
	private LinearLayout ver6;
	private ImageView imageview82;
	private TextView textview80;
	private ImageView imageview83;
	private TextView textview81;
	private ImageView imageview84;
	private TextView textview82;
	private ImageView imageview85;
	private TextView textview83;
	private ImageView imageview86;
	private TextView textview84;
	private ImageView imageview87;
	private TextView textview85;
	private ImageView imageview22;
	private TextView textview23;
	private TextView vermc;
	private LinearLayout linear135;
	private Button button1;
	private ScrollView vscroll3;
	private LinearLayout linear116;
	private LinearLayout linear117;
	private LinearLayout versionmenu;
	private LinearLayout accmenu;
	private LinearLayout client;
	private TextView textview28;
	private LinearLayout linear85;
	private TextView textview29;
	private LinearLayout linear134;
	private LinearLayout linear128;
	private LinearLayout linear130;
	private LinearLayout linear127;
	private LinearLayout linear132;
	private LinearLayout linear118;
	private LinearLayout linear86;
	private TextView English;
	private LinearLayout linear32;
	private ImageView imageview25;
	private ImageView bttonf;
	private TextView javalctext;
	private TextView luutru;
	private TextView textview39;
	private TextView textview40;
	private LinearLayout linear131;
	private EditText op1;
	private EditText op2;
	private TextView ramUsageTextView;
	private SeekBar seekbar1;
	private TextView sure;
	private TextView save;
	private TextView cottruyen;
	private TextView textview86;
	private LinearLayout linear120;
	private LinearLayout linear121;
	private LinearLayout linear122;
	private LinearLayout linear123;
	private ImageView imageview26;
	private TextView q1;
	private ImageView imageview38;
	private TextView q5;
	private ImageView imageview33;
	private TextView q2;
	private ImageView imageview39;
	private TextView q6;
	private ImageView imageview34;
	private TextView q3;
	private ImageView imageview40;
	private TextView q7;
	private ImageView imageview35;
	private TextView q4;
	private ImageView imageview41;
	private TextView q8;
	private LinearLayout linear28;
	private CardView cardview2;
	private LinearLayout linear29;
	private ImageView avatar;
	private TextView steve;
	private LinearLayout linear137;
	private TextView accounttext;
	private ImageView xbicon;
	private LinearLayout linear155;
	private LinearLayout linear156;
	private LinearLayout linear157;
	private LinearLayout linear158;
	private LinearLayout linear160;
	private ImageView imageview69;
	private TextView textview65;
	private ImageView imageview70;
	private TextView textview66;
	private ImageView imageview71;
	private TextView textview67;
	private ImageView imageview72;
	private TextView e4;
	private ImageView imageview73;
	private TextView textview69;
	private ImageView imageview74;
	private TextView textview70;
	private ImageView imageview75;
	private TextView textview71;
	private ImageView imageview76;
	private TextView textview72;
	private ImageView imageview79;
	private TextView textview75;
	private ImageView imageview80;
	private TextView textview76;
	private WebView webskin;
	private LinearLayout linear89;
	private TextView textview30;
	private TextView error;
	private LinearLayout linear100;
	private Button button7;
	private LinearLayout aboutsetting;
	private LinearLayout linear73;
	private LinearLayout linear74;
	private LinearLayout linear75;
	private LinearLayout linear76;
	private LinearLayout linear79;
	private LinearLayout linear80;
	private LinearLayout linear81;
	private LinearLayout linear82;
	private LinearLayout linear83;
	private LinearLayout linear78;
	private TextView launchertext1;
	private TextView launchertext;
	private TextView boottraptext;
	private TextView boottraptext1;
	private TextView uitext;
	private TextView uitext1;
	private TextView cretext;
	private TextView cretext1;
	private TextView cretext2;
	private TextView cretext3;
	private TextView admintext;
	private TextView admintext1;
	private TextView admintext2;
	
	private Intent i = new Intent();
	private SoundPool sound;
	private SharedPreferences monerako;
	private SharedPreferences jv;
	private TimerTask t;
	private FirebaseAuth auth;
	private OnCompleteListener<AuthResult> _auth_create_user_listener;
	private OnCompleteListener<AuthResult> _auth_sign_in_listener;
	private OnCompleteListener<Void> _auth_reset_password_listener;
	private OnCompleteListener<Void> auth_updateEmailListener;
	private OnCompleteListener<Void> auth_updatePasswordListener;
	private OnCompleteListener<Void> auth_emailVerificationSentListener;
	private OnCompleteListener<Void> auth_deleteUserListener;
	private OnCompleteListener<Void> auth_updateProfileListener;
	private OnCompleteListener<AuthResult> auth_phoneAuthListener;
	private OnCompleteListener<AuthResult> auth_googleSignInListener;
	
	private DatabaseReference UDB = _firebase.getReference("users");
	private ChildEventListener _UDB_child_listener;
	
	@Override
	protected void onCreate(Bundle _savedInstanceState) {
		super.onCreate(_savedInstanceState);
		setContentView(R.layout.javalauncher);
		initialize(_savedInstanceState);
		FirebaseApp.initializeApp(this);
		initializeLogic();
	}
	
	private void initialize(Bundle _savedInstanceState) {
		linear1 = findViewById(R.id.linear1);
		linear2 = findViewById(R.id.linear2);
		linear5 = findViewById(R.id.linear5);
		accountbutton = findViewById(R.id.accountbutton);
		linear10 = findViewById(R.id.linear10);
		bedrock = findViewById(R.id.bedrock);
		linear12 = findViewById(R.id.linear12);
		linear8 = findViewById(R.id.linear8);
		accountwhite = findViewById(R.id.accountwhite);
		imageview5 = findViewById(R.id.imageview5);
		playername = findViewById(R.id.playername);
		newwhite = findViewById(R.id.newwhite);
		imageview2 = findViewById(R.id.imageview2);
		textview5 = findViewById(R.id.textview5);
		mainwhite = findViewById(R.id.mainwhite);
		imageview3 = findViewById(R.id.imageview3);
		textview4 = findViewById(R.id.textview4);
		communitywhite = findViewById(R.id.communitywhite);
		imageview4 = findViewById(R.id.imageview4);
		textview3 = findViewById(R.id.textview3);
		linear133 = findViewById(R.id.linear133);
		linear13 = findViewById(R.id.linear13);
		newswhite = findViewById(R.id.newswhite);
		imageview44 = findViewById(R.id.imageview44);
		moi = findViewById(R.id.moi);
		settingwhite = findViewById(R.id.settingwhite);
		imageview7 = findViewById(R.id.imageview7);
		textview2 = findViewById(R.id.textview2);
		linear15 = findViewById(R.id.linear15);
		navigationbar = findViewById(R.id.navigationbar);
		javabr = findViewById(R.id.javabr);
		settingsbr = findViewById(R.id.settingsbr);
		skinmenu = findViewById(R.id.skinmenu);
		accountmenu = findViewById(R.id.accountmenu);
		vscroll1 = findViewById(R.id.vscroll1);
		title = findViewById(R.id.title);
		nut1 = findViewById(R.id.nut1);
		nut2 = findViewById(R.id.nut2);
		nut3 = findViewById(R.id.nut3);
		nut4 = findViewById(R.id.nut4);
		nut5 = findViewById(R.id.nut5);
		nut6 = findViewById(R.id.nut6);
		nut7 = findViewById(R.id.nut7);
		textview8 = findViewById(R.id.textview8);
		Thanhxanh1 = findViewById(R.id.Thanhxanh1);
		textview24 = findViewById(R.id.textview24);
		thanhxanh2 = findViewById(R.id.thanhxanh2);
		textview25 = findViewById(R.id.textview25);
		thanhxanh3 = findViewById(R.id.thanhxanh3);
		textview26 = findViewById(R.id.textview26);
		thanhxanh4 = findViewById(R.id.thanhxanh4);
		textview34 = findViewById(R.id.textview34);
		thanhxanh5 = findViewById(R.id.thanhxanh5);
		textview79 = findViewById(R.id.textview79);
		thanhxanh6 = findViewById(R.id.thanhxanh6);
		textview78 = findViewById(R.id.textview78);
		thanhxanh7 = findViewById(R.id.thanhxanh7);
		linear45 = findViewById(R.id.linear45);
		linear42 = findViewById(R.id.linear42);
		linear40 = findViewById(R.id.linear40);
		imageview23 = findViewById(R.id.imageview23);
		keover = findViewById(R.id.keover);
		srr = findViewById(R.id.srr);
		linear161 = findViewById(R.id.linear161);
		ver1 = findViewById(R.id.ver1);
		ver2 = findViewById(R.id.ver2);
		ver3 = findViewById(R.id.ver3);
		ver4 = findViewById(R.id.ver4);
		ver5 = findViewById(R.id.ver5);
		ver6 = findViewById(R.id.ver6);
		imageview82 = findViewById(R.id.imageview82);
		textview80 = findViewById(R.id.textview80);
		imageview83 = findViewById(R.id.imageview83);
		textview81 = findViewById(R.id.textview81);
		imageview84 = findViewById(R.id.imageview84);
		textview82 = findViewById(R.id.textview82);
		imageview85 = findViewById(R.id.imageview85);
		textview83 = findViewById(R.id.textview83);
		imageview86 = findViewById(R.id.imageview86);
		textview84 = findViewById(R.id.textview84);
		imageview87 = findViewById(R.id.imageview87);
		textview85 = findViewById(R.id.textview85);
		imageview22 = findViewById(R.id.imageview22);
		textview23 = findViewById(R.id.textview23);
		vermc = findViewById(R.id.vermc);
		linear135 = findViewById(R.id.linear135);
		button1 = findViewById(R.id.button1);
		vscroll3 = findViewById(R.id.vscroll3);
		linear116 = findViewById(R.id.linear116);
		linear117 = findViewById(R.id.linear117);
		versionmenu = findViewById(R.id.versionmenu);
		accmenu = findViewById(R.id.accmenu);
		client = findViewById(R.id.client);
		textview28 = findViewById(R.id.textview28);
		linear85 = findViewById(R.id.linear85);
		textview29 = findViewById(R.id.textview29);
		linear134 = findViewById(R.id.linear134);
		linear128 = findViewById(R.id.linear128);
		linear130 = findViewById(R.id.linear130);
		linear127 = findViewById(R.id.linear127);
		linear132 = findViewById(R.id.linear132);
		linear118 = findViewById(R.id.linear118);
		linear86 = findViewById(R.id.linear86);
		English = findViewById(R.id.English);
		linear32 = findViewById(R.id.linear32);
		imageview25 = findViewById(R.id.imageview25);
		bttonf = findViewById(R.id.bttonf);
		javalctext = findViewById(R.id.javalctext);
		luutru = findViewById(R.id.luutru);
		textview39 = findViewById(R.id.textview39);
		textview40 = findViewById(R.id.textview40);
		linear131 = findViewById(R.id.linear131);
		op1 = findViewById(R.id.op1);
		op2 = findViewById(R.id.op2);
		ramUsageTextView = findViewById(R.id.ramUsageTextView);
		seekbar1 = findViewById(R.id.seekbar1);
		sure = findViewById(R.id.sure);
		save = findViewById(R.id.save);
		cottruyen = findViewById(R.id.cottruyen);
		textview86 = findViewById(R.id.textview86);
		linear120 = findViewById(R.id.linear120);
		linear121 = findViewById(R.id.linear121);
		linear122 = findViewById(R.id.linear122);
		linear123 = findViewById(R.id.linear123);
		imageview26 = findViewById(R.id.imageview26);
		q1 = findViewById(R.id.q1);
		imageview38 = findViewById(R.id.imageview38);
		q5 = findViewById(R.id.q5);
		imageview33 = findViewById(R.id.imageview33);
		q2 = findViewById(R.id.q2);
		imageview39 = findViewById(R.id.imageview39);
		q6 = findViewById(R.id.q6);
		imageview34 = findViewById(R.id.imageview34);
		q3 = findViewById(R.id.q3);
		imageview40 = findViewById(R.id.imageview40);
		q7 = findViewById(R.id.q7);
		imageview35 = findViewById(R.id.imageview35);
		q4 = findViewById(R.id.q4);
		imageview41 = findViewById(R.id.imageview41);
		q8 = findViewById(R.id.q8);
		linear28 = findViewById(R.id.linear28);
		cardview2 = findViewById(R.id.cardview2);
		linear29 = findViewById(R.id.linear29);
		avatar = findViewById(R.id.avatar);
		steve = findViewById(R.id.steve);
		linear137 = findViewById(R.id.linear137);
		accounttext = findViewById(R.id.accounttext);
		xbicon = findViewById(R.id.xbicon);
		linear155 = findViewById(R.id.linear155);
		linear156 = findViewById(R.id.linear156);
		linear157 = findViewById(R.id.linear157);
		linear158 = findViewById(R.id.linear158);
		linear160 = findViewById(R.id.linear160);
		imageview69 = findViewById(R.id.imageview69);
		textview65 = findViewById(R.id.textview65);
		imageview70 = findViewById(R.id.imageview70);
		textview66 = findViewById(R.id.textview66);
		imageview71 = findViewById(R.id.imageview71);
		textview67 = findViewById(R.id.textview67);
		imageview72 = findViewById(R.id.imageview72);
		e4 = findViewById(R.id.e4);
		imageview73 = findViewById(R.id.imageview73);
		textview69 = findViewById(R.id.textview69);
		imageview74 = findViewById(R.id.imageview74);
		textview70 = findViewById(R.id.textview70);
		imageview75 = findViewById(R.id.imageview75);
		textview71 = findViewById(R.id.textview71);
		imageview76 = findViewById(R.id.imageview76);
		textview72 = findViewById(R.id.textview72);
		imageview79 = findViewById(R.id.imageview79);
		textview75 = findViewById(R.id.textview75);
		imageview80 = findViewById(R.id.imageview80);
		textview76 = findViewById(R.id.textview76);
		webskin = findViewById(R.id.webskin);
		webskin.getSettings().setJavaScriptEnabled(true);
		webskin.getSettings().setSupportZoom(true);
		linear89 = findViewById(R.id.linear89);
		textview30 = findViewById(R.id.textview30);
		error = findViewById(R.id.error);
		linear100 = findViewById(R.id.linear100);
		button7 = findViewById(R.id.button7);
		aboutsetting = findViewById(R.id.aboutsetting);
		linear73 = findViewById(R.id.linear73);
		linear74 = findViewById(R.id.linear74);
		linear75 = findViewById(R.id.linear75);
		linear76 = findViewById(R.id.linear76);
		linear79 = findViewById(R.id.linear79);
		linear80 = findViewById(R.id.linear80);
		linear81 = findViewById(R.id.linear81);
		linear82 = findViewById(R.id.linear82);
		linear83 = findViewById(R.id.linear83);
		linear78 = findViewById(R.id.linear78);
		launchertext1 = findViewById(R.id.launchertext1);
		launchertext = findViewById(R.id.launchertext);
		boottraptext = findViewById(R.id.boottraptext);
		boottraptext1 = findViewById(R.id.boottraptext1);
		uitext = findViewById(R.id.uitext);
		uitext1 = findViewById(R.id.uitext1);
		cretext = findViewById(R.id.cretext);
		cretext1 = findViewById(R.id.cretext1);
		cretext2 = findViewById(R.id.cretext2);
		cretext3 = findViewById(R.id.cretext3);
		admintext = findViewById(R.id.admintext);
		admintext1 = findViewById(R.id.admintext1);
		admintext2 = findViewById(R.id.admintext2);
		monerako = getSharedPreferences("monerako", Activity.MODE_PRIVATE);
		jv = getSharedPreferences("jv", Activity.MODE_PRIVATE);
		auth = FirebaseAuth.getInstance();
		
		accountbutton.setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View _view) {
				_hidewhitebar();
				javabr.setVisibility(View.GONE);
				settingsbr.setVisibility(View.VISIBLE);
				skinmenu.setVisibility(View.GONE);
				accmenu.setVisibility(View.VISIBLE);
				tit