package com.mojang.minecraftVN;

import android.Manifest;
import android.animation.*;
import android.app.*;
import android.app.Activity;
import android.app.AlertDialog;
import android.content.*;
import android.content.DialogInterface;
import android.content.Intent;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.content.res.*;
import android.graphics.*;
import android.graphics.Typeface;
import android.graphics.drawable.*;
import android.media.*;
import android.media.SoundPool;
import android.net.*;
import android.net.Uri;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.widget.*;
import android.widget.ArrayAdapter;
import android.widget.BaseAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ListView;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;
import androidx.fragment.app.DialogFragment;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import androidx.webkit.*;
import com.blogspot.atifsoftwares.animatoolib.*;
import com.bumptech.glide.Glide;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.FirebaseApp;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.ChildEventListener;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.GenericTypeIndicator;
import com.google.firebase.database.ValueEventListener;
import com.zip4j.*;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Timer;
import java.util.TimerTask;
import java.util.regex.*;
import org.json.*;
import java.io.*;
import java.util.zip.*;
import androidx.documentfile.provider.DocumentFile;
import android.provider.DocumentsContract;
import android.database.*;
import android.provider.DocumentsContract.Document;

public class MainmenuActivity extends AppCompatActivity {
	
	private Timer _timer = new Timer();
	private FirebaseDatabase _firebase = FirebaseDatabase.getInstance();
	
	private boolean a = false;
	private double sef = 0;
	Uri zip;
	int NEW_FOLDER_REQUEST_CODE;
	private String permission_obb = "";
	private String permission = "";
	Uri muri;
	DocumentFile mfile;
	DocumentFile mfile1;
	Uri uri2;
	Uri desturi;
	Uri parenturi;
	DocumentFile parentfile;
	DocumentFile delet;
	
	private ArrayList<Double> images = new ArrayList<>();
	private ArrayList<String> cc = new ArrayList<>();
	private ArrayList<HashMap<String, Object>> project_list = new ArrayList<>();
	private ArrayList<String> project_str = new ArrayList<>();
	
	private LinearLayout linear1;
	private LinearLayout menustore;
	private LinearLayout profile;
	private LinearLayout menuserver;
	private LinearLayout menurelease;
	private LinearLayout menufull;
	private LinearLayout menuskin;
	private LinearLayout linear24;
	private LinearLayout linear20;
	private LinearLayout linear21;
	private LinearLayout linear2;
	private LinearLayout linear19;
	private LinearLayout linear6;
	private LinearLayout linear14;
	private TextView Minecrafttitle;
	private ImageView imageview3;
	private LinearLayout linear23;
	private HorizontalScrollView hscroll1;
	private LinearLayout thanhkeo;
	private LinearLayout linear8;
	private LinearLayout play;
	private LinearLayout skin;
	private LinearLayout store;
	private LinearLayout phathanh;
	private LinearLayout danhsach;
	private LinearLayout caidat;
	private LinearLayout linear147;
	private TextView textplay;
	private LinearLayout thanhxanh;
	private TextView textskin;
	private LinearLayout thanh2;
	private TextView textmarket;
	private LinearLayout thanh3;
	private TextView textnotes;
	private LinearLayout thanh4;
	private TextView textsvlist;
	private LinearLayout Thanhxanh5;
	private TextView creator;
	private LinearLayout thanhxanh6;
	private TextView version;
	private LinearLayout thanhxanh7;
	private LinearLayout linear71;
	private HorizontalScrollView hscroll2;
	private LinearLayout linear_project;
	private EditText edittext2;
	private ImageView hide;
	private LinearLayout linear72;
	private LinearLayout linear73;
	private LinearLayout linear74;
	private LinearLayout linear76;
	private LinearLayout dialog;
	private TextView all;
	private LinearLayout x1;
	private TextView texture;
	private LinearLayout x2;
	private TextView map;
	private LinearLayout x4;
	private TextView dia;
	private LinearLayout x5;
	private ListView listview_project;
	private LinearLayout savebt;
	private TextView UnderlinedTextView;
	private ScrollView thanhprofile;
	private Button manifestexportbuttn;
	private LinearLayout linear150;
	private EditText manifesttext;
	private LinearLayout versionmenu;
	private LinearLayout linear154;
	private LinearLayout linear155;
	private LinearLayout linear156;
	private ImageView imageview35;
	private TextView q1;
	private ImageView imageview41;
	private TextView q2;
	private ImageView imageview36;
	private TextView q5;
	private ImageView imageview42;
	private TextView q11;
	private ImageView imageview37;
	private TextView q6;
	private ImageView imageview43;
	private TextView q12;
	private ScrollView vscroll4;
	private LinearLayout linear120;
	private LinearLayout linear121;
	private LinearLayout linear122;
	private LinearLayout linear123;
	private LinearLayout linear124;
	private LinearLayout linear125;
	private LinearLayout linear126;
	private LinearLayout linear127;
	private LinearLayout linear128;
	private LinearLayout linear129;
	private LinearLayout linear130;
	private LinearLayout linear131;
	private LinearLayout linear132;
	private TextView textview57;
	private TextView textview58;
	private ImageView imageview24;
	private LinearLayout linear133;
	private LinearLayout linear134;
	private LinearLayout linear135;
	private TextView textview59;
	private TextView textview60;
	private ImageView imageview25;
	private LinearLayout linear136;
	private LinearLayout linear137;
	private LinearLayout linear138;
	private TextView textview61;
	private TextView textview62;
	private ImageView imageview26;
	private LinearLayout linear139;
	private LinearLayout linear140;
	private LinearLayout linear141;
	private TextView textview63;
	private TextView textview64;
	private ImageView imageview27;
	private LinearLayout linear142;
	private LinearLayout linear143;
	private LinearLayout linear144;
	private TextView textview65;
	private TextView textview66;
	private ImageView imageview28;
	private ScrollView vscroll3;
	private LinearLayout linear4;
	private LinearLayout linear5;
	private LinearLayout linear108;
	private LinearLayout linear7;
	private TextView cua2;
	private LinearLayout linear109;
	private TextView cua3;
	private LinearLayout linear119;
	private TextView cua4;
	private TextView thaydoi1;
	private TextView cua1;
	private TextView thaydoi2;
	private TextView thaydoi3;
	private TextView thaydoi4;
	private LinearLayout playfull;
	private ScrollView vscroll1;
	private ImageView mainbackground;
	private Button button1;
	private LinearLayout linear37;
	private LinearLayout paperdoll;
	private LinearLayout linear42;
	private LinearLayout linear47;
	private LinearLayout linear55;
	private LinearLayout linear56;
	private LinearLayout linear60;
	private LinearLayout linear61;
	private LinearLayout linear69;
	private LinearLayout linear65;
	private ImageView imageview4;
	private LinearLayout linear39;
	private LinearLayout linear40;
	private LinearLayout linear41;
	private TextView textpaper;
	private TextView textview4;
	private TextView textview5;
	private ImageView imageview6;
	private LinearLayout linear48;
	private LinearLayout linear49;
	private LinearLayout linear50;
	private TextView paperdoll2;
	private TextView textview9;
	private TextView textview10;
	private ImageView imageview8;
	private LinearLayout linear57;
	private LinearLayout linear58;
	private LinearLayout linear59;
	private TextView musicingame;
	private TextView textview15;
	private TextView textview16;
	private ImageView imageview9;
	private LinearLayout linear62;
	private LinearLayout linear63;
	private LinearLayout linear64;
	private TextView lowshader;
	private TextView textview18;
	private TextView textview19;
	private ImageView imageview10;
	private LinearLayout linear66;
	private LinearLayout linear67;
	private LinearLayout linear68;
	private TextView market;
	private TextView textview21;
	private TextView textview22;
	private WebView webskin;
	
	private TimerTask t;
	private SoundPool sound;
	private Intent i = new Intent();
	private SharedPreferences sp;
	private AlertDialog.Builder permission_file;
	private FirebaseAuth auth;
	private OnCompleteListener<AuthResult> _auth_create_user_listener;
	private OnCompleteListener<AuthResult> _auth_sign_in_listener;
	private OnCompleteListener<Void> _auth_reset_password_listener;
	private OnCompleteListener<Void> auth_updateEmailListener;
	private OnCompleteListener<Void> auth_updatePasswordListener;
	private OnCompleteListener<Void> auth_emailVerificationSentListener;
	private OnCompleteListener<Void> auth_deleteUserListener;
	private OnCompleteListener<Void> auth_updateProfileListener;
	private OnCompleteListener<AuthResult> auth_phoneAuthListener;
	private OnCompleteListener<AuthResult> auth_googleSignInListener;
	
	private Intent intent = new Intent();
	private SharedPreferences project_data;
	private DatabaseReference project = _firebase.getReference("project");
	private ChildEventListener _project_child_listener;
	private SharedPreferences jv;
	
	@Override
	protected void onCreate(Bundle _savedInstanceState) {
		super.onCreate(_savedInstanceState);
		setContentView(R.layout.mainmenu);
		initialize(_savedInstanceState);
		FirebaseApp.initializeApp(this);
		
		if (ContextCompat.checkSelfPermission(this, Manifest.permission.READ_EXTERNAL_STORAGE) == PackageManager.PERMISSION_DENIED
		|| ContextCompat.checkSelfPermission(this, Manifest.permission.WRITE_EXTERNAL_STORAGE) == PackageManager.PERMISSION_DENIED) {
			ActivityCompat.requestPermissions(this, new String[] {Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE}, 1000);
		} else {
			initializeLogic();
		}
	}
	
	@Override
	public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
		super.onRequestPermissionsResult(requestCode, permissions, grantResults);
		if (requestCode == 1000) {
			initializeLogic();
		}
	}
	
	private void initialize(Bundle _savedInstanceState) {
		linear1 = findViewById(R.id.linear1);
		menustore = findViewById(R.id.menustore);
		profile = findViewById(R.id.profile);
		menuserver = findViewById(R.id.menuserver);
		menurelease = findViewById(R.id.menurelease);
		menufull = findViewById(R.id.menufull);
		menuskin = findViewById(R.id.menuskin);
		linear24 = findViewById(R.id.linear24);
		linear20 = findViewById(R.id.linear20);
		linear21 = findViewById(R.id.linear21);
		linear2 = findViewById(R.id.linear2);
		linear19 = findViewById(R.id.linear19);
		linear6 = findViewById(R.id.linear6);
		linear14 = findViewById(R.id.linear14);
		Minecrafttitle = findViewById(R.id.Minecrafttitle);
		imageview3 = findViewById(R.id.imageview3);
		linear23 = findViewById(R.id.linear23);
		hscroll1 = findViewById(R.id.hscroll1);
		thanhkeo = findViewById(R.id.thanhkeo);
		linear8 = findViewById(R.id.linear8);
		play = findViewById(R.id.play);
		skin = findViewById(R.id.skin);
		store = findViewById(R.id.store);
		phathanh = findViewById(R.id.phathanh);
		danhsach = findViewById(R.id.danhsach);
		caidat = findViewById(R.id.caidat);
		linear147 = findViewById(R.id.linear147);
		textplay = findViewById(R.id.textplay);
		thanhxanh = findViewById(R.id.thanhxanh);
		textskin = findViewById(R.id.textskin);
		thanh2 = findViewById(R.id.thanh2);
		textmarket = findViewById(R.id.textmarket);
		thanh3 = findViewById(R.id.thanh3);
		textnotes = findViewById(R.id.textnotes);
		thanh4 = findViewById(R.id.thanh4);
		textsvlist = findViewById(R.id.textsvlist);
		Thanhxanh5 = findViewById(R.id.Thanhxanh5);
		creator = findViewById(R.id.creator);
		thanhxanh6 = findViewById(R.id.thanhxanh6);
		version = findViewById(R.id.version);
		thanhxanh7 = findViewById(R.id.thanhxanh7);
		linear71 = findViewById(R.id.linear71);
		hscroll2 = findViewById(R.id.hscroll2);
		linear_project = findViewById(R.id.linear_project);
		edittext2 = findViewById(R.id.edittext2);
		hide = findViewById(R.id.hide);
		linear72 = findViewById(R.id.linear72);
		linear73 = findViewById(R.id.linear73);
		linear74 = findViewById(R.id.linear74);
		linear76 = findViewById(R.id.linear76);
		dialog = findViewById(R.id.dialog);
		all = findViewById(R.id.all);
		x1 = findViewById(R.id.x1);
		texture = findViewById(R.id.texture);
		x2 = findViewById(R.id.x2);
		map = findViewById(R.id.map);
		x4 = findViewById(R.id.x4);
		dia = findViewById(R.id.dia);
		x5 = findViewById(R.id.x5);
		listview_project = findViewById(R.id.listview_project);
		savebt = findViewById(R.id.savebt);
		UnderlinedTextView = findViewById(R.id.UnderlinedTextView);
		thanhprofile = findViewById(R.id.thanhprofile);
		manifestexportbuttn = findViewById(R.id.manifestexportbuttn);
		linear150 = findViewById(R.id.linear150);
		manifesttext = findViewById(R.id.manifesttext);
		versionmenu = findViewById(R.id.versionmenu);
		linear154 = findViewById(R.id.linear154);
		linear155 = findViewById(R.id.linear155);
		linear156 = findViewById(R.id.linear156);
		imageview35 = findViewById(R.id.imageview35);
		q1 = findViewById(R.id.q1);
		imageview41 = findViewById(R.id.imageview41);
		q2 = findViewById(R.id.q2);
		imageview36 = findViewById(R.id.imageview36);
		q5 = findViewById(R.id.q5);
		imageview42 = findViewById(R.id.imageview42);
		q11 = findViewById(R.id.q11);
		imageview37 = findViewById(R.id.imageview37);
		q6 = findViewById(R.id.q6);
		imageview43 = findViewById(R.id.imageview43);
		q12 = findViewById(R.id.q12);
		vscroll4 = findViewById(R.id.vscroll4);
		linear120 = findViewById(R.id.linear120);
		linear121 = findViewById(R.id.linear121);
		linear122 = findViewById(R.id.linear122);
		linear123 = findViewById(R.id.linear123);
		linear124 = findViewById(R.id.linear124);
		linear125 = findViewById(R.id.linear125);
		linear126 = findViewById(R.id.linear126);
		linear127 = findViewById(R.id.linear127);
		linear128 = findViewById(R.id.linear128);
		linear129 = findViewById(R.id.linear129);
		linear130 = findViewById(R.id.linear130);
		linear131 = findViewById(R.id.linear131);
		linear132 = findViewById(R.id.linear132);
		textview57 = findViewById(R.id.textview57);
		textview58 = findViewById(R.id.textview58);
		imageview24 = findViewById(R.id.imageview24);
		linear133 = findViewById(R.id.linear133);
		linear134 = findViewById(R.id.linear134);
		linear135 = findViewById(R.id.linear135);
		textview59 = findViewById(R.id.textview59);
		textview60 = findViewById(R.id.textview60);
		imageview25 = findViewById(R.id.imageview25);
		linear136 = findViewById(R.id.linear136);
		linear137 = findViewById(R.id.linear137);
		linear138 = findViewById(R.id.linear138);
		textview61 = findViewById(R.id.textview61);
		textview62 = findViewById(R.id.textview62);
		imageview26 = findViewById(R.id.imageview26);
		linear139 = findViewById(R.id.linear139);
		linear140 = findViewById(R.id.linear140);
		linear141 = findViewById(R.id.linear141);
		textview63 = findViewById(R.id.textview63);
		textview64 = findViewById(R.id.textview64);
		imageview27 = findViewById(R.id.imageview27);
		linear142 = findViewById(R.id.linear142);
		linear143 = findViewById(R.id.linear143);
		linear144 = findViewById(R.id.linear144);
		textview65 = findViewById(R.id.textview65);
		textview66 = findViewById(R.id.textview66);
		imageview28 = findViewById(R.id.imageview28);
		vscroll3 = findViewById(R.id.vscroll3);
		linear4 = findViewById(R.id.linear4);
		linear5 = findViewById(R.id.linear5);
		linear108 = findViewById(R.id.linear108);
		linear7 = findViewById(R.id.linear7);
		cua2 = findViewById(R.id.cua2);
		linear109 = findViewById(R.id.linear109);
		cua3 = findViewById(R.id.cua3);
		linear119 = findViewById(R.id.linear119);
		cua4 = findViewById(R.id.cua4);
		thaydoi1 = findViewById(R.id.thaydoi1);
		cua1 = findViewById(R.id.cua1);
		thaydoi2 = findViewById(R.id.thaydoi2);
		thaydoi3 = findViewById(R.id.thaydoi3);
		thaydoi4 = findViewById(R.id.thaydoi4);
		playfull = findViewById(R.id.playfull);
		vscroll1 = findViewById(R.id.vscroll1);
		mainbackground = findViewById(R.id.mainbackground);
		button1 = findViewById(R.id.button1);
		linear37 = findViewById(R.id.linear37);
		paperdoll = findViewById(R.id.paperdoll);
		linear42 = findViewById(R.id.linear42);
		linear47 = findViewById(R.id.linear47);
		linear55 = findViewById(R.id.linear55);
		linear56 = findViewById(R.id.linear56);
		linear60 = findViewById(R.id.linear60);
		linear61 = findViewById(R.id.linear61);
		linear69 = findViewById(R.id.linear69);
		linear65 = findViewById(R.id.linear65);
		imageview4 = findViewById(R.id.imageview4);
		linear39 = findViewById(R.id.linear39);
		linear40 = findViewById(R.id.linear40);
		linear41 = findViewById(R.id.linear41);
		textpaper = findViewById(R.id.textpaper);
		textview4 = findViewById(R.id.textview4);
		textview5 = findViewById(R.id.textview5);
		imageview6 = findViewById(R.id.imageview6);
		linear48 = findViewById(R.id.linear48);
		linear49 = findViewById(R.id.linear49);
		linear50 = findViewById(R.id.linear50);
		paperdoll2 = findViewById(R.id.paperdoll2);
		textview9 = findViewById(R.id.textview9);
		textview10 = findViewById(R.id.textview10);
		imageview8 = findViewById(R.id.imageview8);
		linear57 = findViewById(R.id.linear57);
		linear58 = findViewById(R.id.linear58);
		linear59 = findViewById(R.id.linear59);
		musicingame = findViewById(R.id.musicingame);
		textview15 = findViewById(R.id.textview15);
		textview16 = findViewById(R.id.textview16);
		imageview9 = findViewById(R.id.imageview9);
		linear62 = findViewById(R.id.linear62);
		linear63 = findViewById(R.id.linear63);
		linear64 = findViewById(R.id.linear64);
		lowshader = findViewById(R.id.lowshader);
		textview18 = findViewById(R.id.textview18);
		textview19 = findViewById(R.id.textview19);
		imageview10 = findViewById(R.id.imageview10);
		linear66 = findViewById(R.id.linear66);
		linear67 = findViewById(R.id.linear67);
		linear68 = findViewById(R.id.linear68);
		market = findViewById(R.id.market);
		textview21 = findViewById(R.id.textview21);
		textview22 = findViewById(R.id.textview22);
		webskin = findViewById(R.id.webskin);
		webskin.getSettings().setJavaScriptEnabled(true);
		webskin.getSettings().setSupportZoom(true);
		sp = getSharedPreferences